

// Export
module.exports = {

home : 'http://localhost:3000/', 
userName : 'tester01',
userPasswords : 'GteteqbQQgSr88SwNExUQv2ydb7xuf8c',
userNamePosition :':nth-child(1) > input',
userPasswordsPosition : ':nth-child(2) > input',
indexTitle : 'Testers Hotel',
indexLoginButton  : '.btn',
// Dash
dashuserNamePosition : '.username',
dashLogOutPosition : '.user > .btn',
roomButton : ':nth-child(1) > .btn', 
billButton : 'div.block:nth-child(3) > a:nth-child(4)',
clientButton : 'div.block:nth-child(2) > a:nth-child(3)',
reservationButton : 'div.block:nth-child(4) > a:nth-child(4)',
verification : 'View',
//Room
goOUTofRoom : ':nth-child(3) > .btn',
creatbutton : 'h2 > .btn',
Roomcreatbutton : 'Create Room',
alldiv : 'div',
room : 'Room 103',
roomimgP : 'div.card:nth-child(3) > div:nth-child(3)',
deleteP : '.menu > :nth-child(2)',
editP : '.menu > :nth-child(1)',
// Edit Room
edroomP : ':nth-child(4) > input',
oldroomnr : '103',
roomnew : '1001',
saveButton : '.blue',
//CreatRoom
categoryPosion : ':nth-child(1) > select',
category : 'Twin',
numberPosion : ':nth-child(2) > input',
number : '103',
floorPosion : ':nth-child(3) > input',
floor : '5',
availablePosion : '.checkbox',
pricePosion : ':nth-child(5) > input',
price : '5000',
featuresPosion : ':nth-child(6) > select',
features : ['ensuite', 'sea_view' ],
//Bill
goOUTofRoom : 'a.btn:nth-child(1)',
//creatbutton : 'h2 > .btn',
Billverification : 'Create Bill',
bill : 'ID: 2',
billimgP : ':nth-child(2) > .action',
deleteP : '.menu > :nth-child(2)',
editP : '.menu > :nth-child(1)',
// Edit Bill
oldValue : '1111',
edbillP : ':nth-child(3) > input',
billnew : '10000',
//CreatBill
allPosion : '#app > :nth-child(2)',
cbillcon : 'New Bill',
valuePosion : 'input', 
value : '1111',
paidPosion : '.checkbox',

//Client
goOUTofRoom : 'a.btn:nth-child(1)',
Clientverification : 'Create Client',
client : 'Test Testsson',
clientimgP : 'div.card:nth-child(3) > div:nth-child(3)',
deleteP : '.menu > :nth-child(2)',
// Edit Client
editP : '.menu > :nth-child(1)',
edClientP : ':nth-child(3) > input',
newclient : 'New Name',
//CreatClient
allPosion : '#app > :nth-child(2)',
cclientcon : 'New Client',
namePosion : ':nth-child(1) > input' ,
nameLabelP : ':nth-child(1) > label',
name : 'Test Testsson',
nameLabel : 'Name',
emailPosion : ':nth-child(2) > input',
emailLabelP : ':nth-child(2) > label',
email : 'test@testsson.com',
emailLabel : 'Email',
telPosion :  ':nth-child(3) > input',
telLabelP : ':nth-child(3) > label',
tel : '111 111 1111',
telLabel : 'Telephone',

// Reservation
goOUTofRoom : 'a.btn:nth-child(1)',
resVerification : 'Create Reservation',
res : 'Test Testsson',
imgP : ':nth-child(2) > .action > img',
deleteP : '.menu > :nth-child(2)',
editP : '.menu > :nth-child(1)',
//EditReservation
newclient : 'New Name',
edstartP : ':nth-child(3) > input',
edendP : ':nth-child(4) > input',
oldstart : '2020-11-01',
oldend : '2021-01-22',
newstart : '2021-04-01',
newend : '2021-04-04',
saveButton : '.blue',
//CreatReservation
allPosion : '#app > :nth-child(2)',
cresvverification : 'New Reservation',
startPosion : ':nth-child(1) > input' ,
startLabelP : ':nth-child(1) > label',
start : '2020-11-01',
startLabel : 'Start (Format YYYY-MM-DD)',
endPosion : ':nth-child(2) > input',
endLabelP : ':nth-child(2) > label',
end : '2021-01-22',
endLabel : 'End (Format YYYY-MM-DD)',
clientPosion : ':nth-child(3) > select' ,
clientLabelP : ':nth-child(3) > label',
client :  'Test Testsson (#3)',
clientLabel : 'Client',
roomPosion :  ':nth-child(4) > select',
roomLabelP : ':nth-child(4) > label',
room :      'Floor 5, Room 103'  ,
roomLabel :  'Room',
idPosion :  ':nth-child(5) > select',
idLabelP : ':nth-child(5) > label',
id : 'ID: 2',
idLabel : 'Bill',





}
